name: Notificacion NTFY

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificaciÃ³n a ntfy
        run: |
          curl -H "Title: Nuevo Push en main" \
               -H "Priority: urgent" \
               -d "Se realizÃ³ un nuevo push al repositorio ðŸš€" \
               https://ntfy.sh/devops-itla
